version: '3.4'
services:
    localstack:
        image: localstack/localstack
        container_name: localstack
        ports:
            - 4566:4566
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock

    terraform:
        image: hashicorp/terraform
        container_name: terraform
        entrypoint: /usr/bin/tail
        command: ["-f", "/dev/null"]
        working_dir: /workspace
        volumes: 
          - $PWD:/workspace

networks:
    default:
        name: localstack
